import type { Metadata } from "next";
import { beVietnamPro } from "@/config/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Country Page - WorldRanks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beVietnamPro.className}>{children}</body>
    </html>
  );
}
