import Image from "next/image";
import type { Metadata } from "next";
import { beVietnamPro } from "@/config/fonts";
import "./globals.css";
import { HeroImage } from "@/components";

export const metadata: Metadata = {
  title: "Country Page - WorldRanks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={beVietnamPro.className}>
        <HeroImage />
        {children}
      </body>
    </html>
  );
}
